### ISSUE TITLE
Installation steps MySQL 8.0.13

### ISSUE THREAD

**Issue by imanasmishra** [Infosys/data-rapid#2]
Could you please let us know the steps for below configuration:

MySQL 8.0.13 (older version MySQL not working macOS Mojave)
 
shiro.ini
--------
ds = com.mysql.cj.jdbc.MysqlDataSource
ds.serverName = localhost
ds.user = root
ds.password = root
ds.databaseName = datagen

application properties:
-----------------------
# Persistance Details
jdbc.driverClassName = com.mysql.cj.jdbc.MysqlDataSource
jdbc.url = jdbc:mysql://localhost:3306/datagen
jdbc.username =root
jdbc.password =root

**Comment by bejoybahuleyan** [comment]
Hi Mishra,
We tried with the latest mysql version 8.0.16 and successfully logged into the application and able to generate data. Requesting to verify the configurations again.

Following are the configuration changes done for the latest mysql version check.

**Maven dependency**

`<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.16</version>
</dependency>`

**application.properties**

`jdbc.driverClassName = com.mysql.cj.jdbc.MysqlDataSource`

**shiro.ini**

`ds = com.mysql.cj.jdbc.MysqlDataSource`

**Comment by imanasmishra** [comment]
Needed to use below URL:
http://localhost:1400/datarapid-1.0/index.html

http://localhost:1400/datarapid-1.0/ -- Old (not working)
